version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "bun"
    directory: "/api"
    schedule:
      interval: "weekly"
      groups:
        api-dependencies:
          patterns:
            - "*"
      ignore:
        - dependency-name: "typescript"
          update-types:
            - "version-update:semver-major"

  - package-ecosystem: "bun"
    directory: "/api/web"
    schedule:
      interval: "weekly"
      groups:
        web-dependencies:
          patterns:
            - "*"
      ignore:
        - dependency-name: "typescript"
          update-types:
            - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/api"
    schedule:
      interval: "weekly"
    groups:
      docker-images:
        patterns:
          - "*"
