export const openApiDocument = {
  openapi: '3.1.0',
  info: { title: 'dkrypt API', version: '1.2.0', description: 'Queue decrypt jobs, reuse persistent IPA artifacts, retrieve authenticated downloads, and manage provider-neutral billing.' },
  servers: [{ url: '/' }],
  components: {
    securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer' } },
    schemas: {
      Job: { type: 'object', properties: { id: { type: 'string', format: 'uuid' }, bundleId: { type: 'string' }, status: { type: 'string', enum: ['queued', 'running', 'done', 'failed'] }, progress: { type: 'string' }, source: { type: 'string', enum: ['manual', 'scheduler'] }, channel: { type: 'string', enum: ['appstore', 'testflight'] }, queuedBy: { type: 'string' }, artifactId: { type: 'string' }, artifactUrl: { type: 'string', description: 'Stable API artifact URL. Requires an API key.' }, cacheHit: { type: 'boolean' }, sizeBytes: { type: 'integer' }, sha256: { type: 'string' }, statusUrl: { type: 'string' } } },
      Artifact: { type: 'object', properties: { id: { type: 'string', format: 'uuid' }, bundleId: { type: 'string' }, channel: { type: 'string', enum: ['appstore', 'testflight'] }, versionLabel: { type: 'string' }, buildNumber: { type: 'string' }, sizeBytes: { type: 'integer' }, sha256: { type: 'string' }, createdAt: { type: 'string', format: 'date-time' }, lastAccessedAt: { type: 'string', format: 'date-time' }, accessCount: { type: 'integer' }, fileUrl: { type: 'string' } } },
    BillingSubscription: { type: 'object', properties: { provider: { type: 'string', enum: ['stripe', 'nowpayments', 'legacy'] }, subscriptionId: { type: 'string' }, checkoutId: { type: 'string' }, customerId: { type: 'string' }, priceId: { type: 'string' }, productId: { type: 'string' }, interval: { type: 'string' }, status: { type: 'string' }, plan: { type: 'object', properties: { id: { type: 'string' }, name: { type: 'string' }, amount: { type: 'number' }, currency: { type: 'string' } } }, user: { type: 'object', properties: { id: { type: 'string' }, displayName: { type: 'string' }, username: { type: 'string' }, email: { type: 'string' } } }, nextBilledAt: { type: 'string', format: 'date-time' }, crypto: { type: 'object', properties: { walletAddress: { type: 'string' }, chain: { type: 'string' }, asset: { type: 'string' } } }, tax: { type: 'object', properties: { status: { type: 'string' }, country: { type: 'string' }, postalCode: { type: 'string' }, transactionId: { type: 'string' } } }, lastCharge: { type: 'object', properties: { id: { type: 'string' }, status: { type: 'string' }, at: { type: 'string', format: 'date-time' }, txHash: { type: 'string' }, failureReason: { type: 'string' }, graceUntil: { type: 'string', format: 'date-time' } } } } },
      Error: { type: 'object', required: ['error'], properties: { error: { type: 'string' } } },
    },
  },
  security: [{ bearerAuth: [] }],
  paths: {
    '/v1/decrypts': { post: { summary: 'Queue or reuse a decrypt by release selector', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['bundleId'], properties: { bundleId: { type: 'string' }, version: { type: 'string', pattern: '^v?\\d+(?:\\.\\d+)*(?:_\\d+)?$' } } } } } }, responses: { '200': { description: 'Completed job with a persistent artifact cache hit', content: { 'application/json': { schema: { $ref: '#/components/schemas/Job' } } } }, '202': { description: 'Queued job', content: { 'application/json': { schema: { $ref: '#/components/schemas/Job' } } } }, '400': { description: 'Invalid request' }, '403': { description: 'API key scope denied' }, '404': { description: 'Version not found' } } } },
    '/v1/decrypt': { get: { summary: 'Decrypt an App Store app', parameters: [{ name: 'bundleId', in: 'query', required: true, schema: { type: 'string' }, example: 'com.hammerandchisel.discord' }, { name: 'externalVersionId', in: 'query', schema: { type: 'string' } }, { name: 'version', in: 'query', schema: { type: 'string', pattern: '^v?\\d+(?:\\.\\d+)*(?:_\\d+)?$' } }, { name: 'Idempotency-Key', in: 'header', schema: { type: 'string', maxLength: 200 }, description: 'Returns the original job for an equivalent retry during the retention window.' }], responses: { '200': { description: 'Completed IPA file' }, '202': { description: 'Queued job', content: { 'application/json': { schema: { $ref: '#/components/schemas/Job' } } } }, '400': { description: 'Invalid request', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } }, '401': { description: 'Invalid API key' }, '409': { description: 'Idempotency key was reused with different input' } } } },
    '/v1/jobs/{id}': { get: { summary: 'Get job status', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], responses: { '200': { description: 'Job status', content: { 'application/json': { schema: { $ref: '#/components/schemas/Job' } } } }, '404': { description: 'Job not found' } } } },
    '/v1/artifacts': { get: { summary: 'List IPA artifacts', parameters: [{ name: 'q', in: 'query', schema: { type: 'string' } }, { name: 'channel', in: 'query', schema: { type: 'string', enum: ['appstore', 'testflight'] } }, { name: 'offset', in: 'query', schema: { type: 'integer' } }, { name: 'limit', in: 'query', schema: { type: 'integer' } }], responses: { '200': { description: 'IPA artifacts', content: { 'application/json': { schema: { type: 'object', properties: { artifacts: { type: 'array', items: { $ref: '#/components/schemas/Artifact' } }, total: { type: 'integer' }, totalBytes: { type: 'integer' }, maxBytes: { type: 'integer' } } } } } } } } },
    '/v1/artifacts/{id}': { get: { summary: 'Get IPA artifact metadata', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], responses: { '200': { description: 'Artifact metadata', content: { 'application/json': { schema: { $ref: '#/components/schemas/Artifact' } } } }, '404': { description: 'Artifact not found' } } } },
    '/v1/artifacts/{id}/file': { get: { summary: 'Download an IPA artifact with an API key', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], responses: { '200': { description: 'IPA file' }, '401': { description: 'API key required' }, '404': { description: 'Artifact not found' } } } },
    '/v1/billing': { get: { summary: 'Read the current account billing state', responses: { '200': { description: 'Provider-neutral billing state' }, '401': { description: 'Session required' } } } },
    '/v1/billing/checkout': { post: { summary: 'Start a Stripe or crypto subscription checkout', parameters: [{ name: 'Idempotency-Key', in: 'header', required: true, schema: { type: 'string', maxLength: 200 } }], requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['planId'], properties: { planId: { type: 'string' }, provider: { type: 'string', enum: ['stripe', 'crypto'], default: 'stripe' }, taxAddress: { type: 'object', properties: { country: { type: 'string' }, postalCode: { type: 'string' }, state: { type: 'string' }, city: { type: 'string' }, line1: { type: 'string' }, line2: { type: 'string' } } } } } } } }, responses: { '201': { description: 'Hosted checkout URL' }, '400': { description: 'Invalid plan, idempotency key, or billing address' }, '409': { description: 'Existing subscription' }, '503': { description: 'Provider not ready' } } } },
    '/v1/billing/cancel': { post: { summary: 'Cancel the current provider subscription', parameters: [{ name: 'Idempotency-Key', in: 'header', required: true, schema: { type: 'string', maxLength: 200 } }], responses: { '200': { description: 'Cancellation accepted' }, '400': { description: 'Missing or invalid idempotency key' }, '404': { description: 'No subscription found' }, '409': { description: 'Provider conflict' } } } },
    '/v1/billing/subscriptions': { get: { summary: 'Manager subscription ledger', parameters: [{ name: 'q', in: 'query', schema: { type: 'string' } }, { name: 'provider', in: 'query', schema: { type: 'string', enum: ['stripe', 'nowpayments', 'legacy'] } }, { name: 'status', in: 'query', schema: { type: 'string' } }], responses: { '200': { description: 'Member subscriptions', content: { 'application/json': { schema: { type: 'object', properties: { subscriptions: { type: 'array', items: { $ref: '#/components/schemas/BillingSubscription' } } } } } } }, '403': { description: 'Billing view permission required' } } } },
    '/v1/billing/provider-status': { get: { summary: 'Manager billing provider readiness', responses: { '200': { description: 'Provider readiness without secrets' }, '403': { description: 'Billing management permission required' } } } },
    '/v1/nowpayments/webhook': { post: { summary: 'Receive verified NOWPayments IPN events', responses: { '200': { description: 'Event accepted' }, '400': { description: 'Invalid signature or event' }, '503': { description: 'Webhook not configured' } } } },
  },
} as const;
