export const openApiDocument = {
  openapi: '3.1.0',
  info: { title: 'dkrypt API', version: '1.1.0', description: 'Queue decrypt jobs, reuse retained IPA artifacts, and retrieve completed files.' },
  servers: [{ url: '/' }],
  components: {
    securitySchemes: { bearerAuth: { type: 'http', scheme: 'bearer' } },
    schemas: {
      Job: { type: 'object', properties: { id: { type: 'string', format: 'uuid' }, bundleId: { type: 'string' }, status: { type: 'string', enum: ['queued', 'running', 'done', 'failed'] }, progress: { type: 'string' }, source: { type: 'string', enum: ['manual', 'scheduler'] }, channel: { type: 'string', enum: ['appstore', 'testflight'] }, queuedBy: { type: 'string' }, artifactId: { type: 'string' }, artifactUrl: { type: 'string' }, cacheHit: { type: 'boolean' }, sizeBytes: { type: 'integer' }, sha256: { type: 'string' }, statusUrl: { type: 'string' }, fileUrl: { type: 'string' } } },
      Artifact: { type: 'object', properties: { id: { type: 'string', format: 'uuid' }, bundleId: { type: 'string' }, channel: { type: 'string', enum: ['appstore', 'testflight'] }, versionLabel: { type: 'string' }, buildNumber: { type: 'string' }, sizeBytes: { type: 'integer' }, sha256: { type: 'string' }, createdAt: { type: 'string', format: 'date-time' }, lastAccessedAt: { type: 'string', format: 'date-time' }, accessCount: { type: 'integer' }, fileUrl: { type: 'string' } } },
      Error: { type: 'object', required: ['error'], properties: { error: { type: 'string' } } },
    },
  },
  security: [{ bearerAuth: [] }],
  paths: {
    '/v1/decrypts': { post: { summary: 'Queue or reuse a decrypt by release selector', requestBody: { required: true, content: { 'application/json': { schema: { type: 'object', required: ['bundleId'], properties: { bundleId: { type: 'string' }, version: { type: 'string', pattern: '^v?\\d+(?:\\.\\d+)*(?:_\\d+)?$' } } } } } }, responses: { '200': { description: 'Completed job with a retained artifact cache hit', content: { 'application/json': { schema: { $ref: '#/components/schemas/Job' } } } }, '202': { description: 'Queued job', content: { 'application/json': { schema: { $ref: '#/components/schemas/Job' } } } }, '400': { description: 'Invalid request' }, '403': { description: 'API key scope denied' }, '404': { description: 'Version not found' } } } },
    '/v1/decrypt': { get: { summary: 'Decrypt an App Store app', parameters: [{ name: 'bundleId', in: 'query', required: true, schema: { type: 'string' }, example: 'com.hammerandchisel.discord' }, { name: 'externalVersionId', in: 'query', schema: { type: 'string' } }, { name: 'version', in: 'query', schema: { type: 'string', pattern: '^v?\\d+(?:\\.\\d+)*(?:_\\d+)?$' } }, { name: 'Idempotency-Key', in: 'header', schema: { type: 'string', maxLength: 200 }, description: 'Returns the original job for an equivalent retry during the retention window.' }], responses: { '200': { description: 'Completed IPA file' }, '202': { description: 'Queued job', content: { 'application/json': { schema: { $ref: '#/components/schemas/Job' } } } }, '400': { description: 'Invalid request', content: { 'application/json': { schema: { $ref: '#/components/schemas/Error' } } } }, '401': { description: 'Invalid API key' }, '409': { description: 'Idempotency key was reused with different input' } } } },
    '/v1/jobs/{id}': { get: { summary: 'Get job status', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], responses: { '200': { description: 'Job status', content: { 'application/json': { schema: { $ref: '#/components/schemas/Job' } } } }, '404': { description: 'Job not found' } } } },
    '/v1/jobs/{id}/file': { get: { summary: 'Download a completed job', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], responses: { '200': { description: 'Completed IPA file' }, '409': { description: 'Job is not complete', content: { 'application/json': { schema: { $ref: '#/components/schemas/Job' } } } } } } },
    '/v1/artifacts': { get: { summary: 'List retained IPA artifacts', parameters: [{ name: 'q', in: 'query', schema: { type: 'string' } }, { name: 'channel', in: 'query', schema: { type: 'string', enum: ['appstore', 'testflight'] } }, { name: 'offset', in: 'query', schema: { type: 'integer' } }, { name: 'limit', in: 'query', schema: { type: 'integer' } }], responses: { '200': { description: 'Retained artifacts', content: { 'application/json': { schema: { type: 'object', properties: { artifacts: { type: 'array', items: { $ref: '#/components/schemas/Artifact' } }, total: { type: 'integer' }, totalBytes: { type: 'integer' }, maxBytes: { type: 'integer' } } } } } } } } },
    '/v1/artifacts/{id}': { get: { summary: 'Get retained artifact metadata', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], responses: { '200': { description: 'Artifact metadata', content: { 'application/json': { schema: { $ref: '#/components/schemas/Artifact' } } } }, '404': { description: 'Artifact not found' } } } },
    '/v1/artifacts/{id}/file': { get: { summary: 'Download a retained IPA artifact', parameters: [{ name: 'id', in: 'path', required: true, schema: { type: 'string', format: 'uuid' } }], responses: { '200': { description: 'IPA file' }, '404': { description: 'Artifact not found' } } } },
  },
} as const;
